### ISSUE TITLE
2 Fehler

### ISSUE THREAD

**Issue by D3nied** [Tutorialwork/ProfessionalBans-Reloaded#3]
`02:37:42 [INFO] §e§lBANS §8• §7§aDie Verbindung mit der MySQL Datenbank wurde erfolgreich hergestellt
02:37:42 [INFO] §e§lBANS §8• §7§aDie Verbindung mit der MySQL Datenbank wurde erfolgreich hergestellt
02:37:42 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'SORTINDEX'
02:37:42 [INFO] §e§lBANS §8• §7§aDie Verbindung mit der MySQL Datenbank wurde erfolgreich hergestellt
02:37:42 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'FIREBASE_TOKEN'
02:37:42 [INFO] §e§lBANS §8• §7§aDie Verbindung mit der MySQL Datenbank wurde erfolgreich hergestellt
02:37:42 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'ONLINE_STATUS'`
kommt beim start des Servers

`02:15:11 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'n der baum fetter werden?', '1575249311339')' at line 1`

immer wenn ein ` in einen satz/wort im chat verwendet wird

**Comment by justinkluever** [comment]
Der Erste fehler kommt weil sowas wie `IF NOT EXISTS` nicht unterstützt wird wenn man `ALTER` befehle nutzt (und das beim start immer versucht diesen befehl auszuführen)

Der zweite fehler könnte sogar eine etwas größere sicherheits bedingte sache sein die man eventuell demnächste beheben sollte um schaden zu vermeiden ^^

**Comment by Tutorialwork** [comment]
Danke für die Meldung. Ich habe diesen Bug nun in Version 2.7 behoben.
