### ISSUE TITLE
Fatal error in Ban Reasons (Webinterface)

### ISSUE THREAD

**Issue by Mobulos** [Tutorialwork/ProfessionalBans-Reloaded#6]
**Serverinformation**
 - Software: BungeeCord
 - Plugin Version: 2.9.2

**Errors**
On Web interface:
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'SORTINDEX' in 'order clause' in C:\XAMPP\htdocs\verwaltung\reasons.php:76 Stack trace: #0 C:\XAMPP\htdocs\verwaltung\reasons.php(76): PDOStatement->execute() #1 {main} thrown in C:\XAMPP\htdocs\verwaltung\reasons.php on line 76

**Describe the bug**
The Error occurs when you got to the "reasons.php" on the Web interface.

**Comment by Tutorialwork** [comment]
Fixed in v3.0 (Currently Pre-Release)
