### ISSUE TITLE
[BUG] Trotz deaktiviert MSG gibt es /msgtoggle noch

### ISSUE THREAD

**Issue by JaHollTV** [Tutorialwork/ProfessionalBans-Reloaded#7]
Paper 1.14.4 Professional Bans 3.0
Wenn man MSG in der Config deaktiviert gibt der /msgtoggle command immer noch den output. Der Command wird also nicht mit deaktiviert

**Comment by Tutorialwork** [comment]
Der Bug wurde in der neusten Version behoben.
